version: '3'
services:
  buildstage:
    image: buildstage
    volumes:
      - /tmp/myvol:/tmp/myvol
  runstage:
    image: runstage
    depends_on:
      - buildstage
    ports:
      - "8080:8080"
    volumes:
      - /tmp/myvol:/tmp/myvol
